name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Fix ESLint permissions
      run: |
        cd frontend
        chmod +x node_modules/.bin/eslint

    - name: Lint the frontend
      run: |
        cd frontend
        npx eslint .
